gemeral frame is finished
andreyDelay/currency-convetrer pull request #1
Opened 2022-04-22 13:03 UTC by andreyDelay

2022-04-22 16:16 UTC, kegisa requested changes

2022-04-22 16:16 UTC, kegisa commented on pom.xml
>        <version>4.11</version>
4  junit зачем?

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ApplicationFlow.java
> +    void startFlow(UserInterface userInterface,
Зачем нам передавать эти объекты каждый раз при вызове? Почему не заинжектил через конструктор?

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ConsoleApplicationFlow.java
> +        private void stopIfExitWasInput(String inputValue) {
что то разметка поплыла, следи за этим, автоформатирование в идее есть

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ConsoleApplicationFlow.java
> +            stopIfExitWasInput(amountOfRubles);
каждый раз этот метод дергаем... давай будем проверять это в юзер интерфейсе и кидать исключение если юзер такое ввел

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ConsoleApplicationFlow.java
> +                System.out.println(targetCurrencyInfo);
это логирование или вывод пользователю?

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/controllers/Controller.java
> +public interface Controller {
не особо понятно почему это контроллер?

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/controllers/Controller.java
> +    CurrencyDto convertCurrency(TokenMoney tokenMoney);
давай передавать просто нужное количество параметров, зачем нам моделька токен мани?

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/controllers/impl/ConsoleControllerImpl.java
> +public class ConsoleControllerImpl implements Controller {
не ясно причем здесь консоль? контроллер может работать и с другими типами интерфейсов

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/controllers/impl/ConsoleControllerImpl.java
> +    @Override
строки надо разделять по логике, посмотри "чистый код" Мартина

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/model/CurrencyRate.java
> +    private Double rate;
почему объектный тип данных а не примитив?

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/JsonFileRepository.java
> +public interface JsonFileRepository extends GenericRepository<CurrencyRate> {
зачем этот интерфейс?

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/GenericRepository.java
> +public interface GenericRepository<T> {
в методах все про курсы валют а в названии класса кажется что это супер обобщенный класс

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/impl/JsonFileRepositoryImpl.java
> +    private final String pathToRepositoryFile = "src/main/resources/currency.json";
путь до файлу не должен быть тут захардкожен, вынеси это в мейн метод

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/utils/Utils.java
> +public class Utils {
Не понятно что это за ютилс

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/utils/Utils.java
> +                throw new Exception();
есть illegalargument

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/utils/Utils.java
> +public class Utils {
скорее это какой то валидатор

2022-04-22 16:16 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/utils/Utils.java
> +    public static void validateParameters(String amountOfRubles, String targetCurrencyCode)
статика здесь зачем?

2022-04-22 17:41 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/app/ConsoleApplicationFlow.java
> +                System.out.println(targetCurrencyInfo);
Это вывод пользователю. Создавал специальный метод в UI, но пропустил момент, исправлю.

2022-04-22 17:43 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/utils/Utils.java
> +public class Utils {
Изначально делал валидатор, удалил и вынес в Utils) Принял - исправлю.

2022-04-22 17:44 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/utils/Utils.java
> +    public static void validateParameters(String amountOfRubles, String targetCurrencyCode)
Слышал что в utils классах обычно статик методы, думал что это бест практис.

2022-04-22 18:26 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/app/ApplicationFlow.java
> +    void startFlow(UserInterface userInterface,
Не разобрался как обязать передавать в конструктор все параметры. 
Был вариант с абстрактным классом с конструктором.
```suggestion
    public abstruct class AbstructApplicationFlow implements ApplicationFlow {
               public AbstructApplicationFlow (UI, Repo, Controlr) {
               
               }
    }
```


У меня и ранее была проблема с пониманием что куда инжектить.
1. Создать целевой объект Reposotiry
2. Создать Controller, приняв Repo
3. Создать UI, приняв Controller
Или
Думал вынести в abstract factory и создавать семейством. Однако тогда нет возможность отдельно заменить слой репо, например, и т.д.

В результате вынес в метод, так как думал что передача единовременно при старте - не критично. 
Другая реализация - другой flow, другие параметры метода.

2022-04-22 19:12 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/controllers/Controller.java
> +public interface Controller {
Некий объект, принимающий данные от UI, совершая операции над ними. 
Расценил это как Controller

2022-04-22 19:13 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/controllers/Controller.java
> +    CurrencyDto convertCurrency(TokenMoney tokenMoney);
Сперва было именно так. Исправляю

2022-04-22 19:19 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/repo/JsonFileRepository.java
> +public interface JsonFileRepository extends GenericRepository<CurrencyRate> {
Реализует типизацию.
Рассуждал что если в будущем будет другой репо, и мы захотим использовать другой тип,
то сможем создать ещё один CSVFileRepository, например, и при желании типизировать другим типом данных.

2022-04-23 07:08 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ApplicationFlow.java
> +    void startFlow(UserInterface userInterface,
В интерфейса и не будет конструктора, просто убери из метоад, а инжекти уже в классе реализации в конструкторе

2022-04-23 07:12 UTC, kegisa requested changes

2022-04-23 07:12 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/JsonFileRepository.java
> +public interface JsonFileRepository extends GenericRepository<CurrencyRate> {
Мы же можем сразу аписать GenericRepository<CyrrencyRate>

2022-04-23 07:12 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/utils/Utils.java
> +    public static void validateParameters(String amountOfRubles, String targetCurrencyCode)
Лучше также этот валидатор инжектить просто там где ты бдуешь его юзать и все

2022-04-23 08:13 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/app/ConsoleApplicationFlow.java
> +            stopIfExitWasInput(amountOfRubles);
Не совсем понял мысль.
Вынес stopIfExitWasInput(amountOfRubles); в UI и останавливаю по той же причине. Про исключение не понял(
![image](https://user-images.githubusercontent.com/61351867/164886343-abe97cda-a2ae-4e66-aa8f-f7e21161fde5.png)

2022-04-25 06:46 UTC, kegisa requested changes

2022-04-25 06:46 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/App.java
> +            Controller controller = new ControllerImpl(repository);
почему это контроллер? Вроде обычный сервис

2022-04-25 06:46 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/App.java
> +            UserInterface userInterface = new ConsoleInterfaceImplementation(controller);
Зачем класс интерфейса юзера инжектит в себя контроллер?

2022-04-25 06:46 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/impl/JsonFileCurrencyRepositoryImpl.java
> +            return null;
null не надо возвращать

2022-04-25 06:46 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/impl/JsonFileCurrencyRepositoryImpl.java
> +        return Arrays.asList(gson.fromJson(jsonReader, CurrencyRate[].class));
Сразу список нельзя считать? не конвертируя массив в список

2022-04-25 06:46 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/view/Impl/ConsoleInterfaceImplementation.java
> +    private final Controller controller;
тут вообще контроллеру не место

2022-04-25 11:54 UTC, kegisa requested changes

2022-04-25 11:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/model/CurrencyRate.java
> +@Builder
зачем здесь билдер?

2022-04-25 11:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/service/CurrencyConvertingService.java
> +    CurrencyDto convertCurrency(String rublesQty, CurrencyRate targetCurrencyInfo);
Не думаю что здесь String уместно

2022-04-25 13:42 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/repo/impl/JsonFileCurrencyRepositoryImpl.java
> +            return null;
Не могу придумать чем заменить null. 
Есть пара идей
Просто вычитывать varName.get(); и ловить исключение NoSuchElementException в вызывающем классе.
Или переделать сигнатуру метода, возвращать Optional.Empty если ничего нет и в вызывающем классе проверять уже.

2022-04-26 11:43 UTC, merged