Spring driven currency service
andreyDelay/currency-convetrer pull request #3
Opened 2022-04-28 14:12 UTC by andreyDelay

Only spring-context dependency had been involved.
`   
<spring-context-version>5.3.19</spring-context-version> 
<dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>${spring-context-version}</version>
    </dependency>
`
Mentioned dependency includes a batch of dependecies: spring-core, spring-expression, spring-aop, and spring-beans. 
It is satisfy to our requrements.

2022-04-28 15:54 UTC, kegisa requested changes

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ApplicationFlow.java
> +@Component
Над интерфейсом не вешается такая аннотация, как спринг создаст объект у интерфейса?

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ConsoleApplicationFlow.java
> +    @Autowired
Разве эта аннотация нужна? Вроде спринг уже сам понимает что надо заинжектить эти бины черзе конструктор если они файнал

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/app/ConsoleApplicationFlow.java
>      public ConsoleApplicationFlow(UserInterface userInterface,
Используй ломбок

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/config/condition/ExternalServiceRepositoryInitializationCondition.java
> +    public boolean matches(ConditionContext context, AnnotatedTypeMetadata metadata) {
Не надо тперь из файла брать , дропай эти классы

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/config/condition/JsonRepositoryInitializationCondition.java
> +    public boolean matches(ConditionContext context, AnnotatedTypeMetadata metadata) {
дроп

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/impl/ExternalServiceCurrencyRepositoryImpl.java
> +    private String pathToRepository;
в дальнейшем вэлью убьирай и через конфигурейшн пропертис делай, когда спринг бут подключишь

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/repo/impl/JsonFileCurrencyRepositoryImpl.java
> +    @Value("${repository-path}")
Аналогично с вэлью

2022-04-28 15:54 UTC, kegisa commented on src/main/java/com/andrey/currencyconverter/validators/Validator.java
>  public class Validator {
Попробуешь заменить этот класс с помощью @Valid аннтоации?

2022-05-01 21:06 UTC, andreyDelay commented on src/main/java/com/andrey/currencyconverter/validators/Validator.java
>  public class Validator {
Всё-таки сделал реализацию валидатора без спрингбут. 
Оказалось не хватало зависимости и ещё кое-чего. Документация docs.jboss.org помогла очень
`<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>7.0.4.Final</version>
</dependency>
`

2022-05-04 16:47 UTC, closed without merging